# Generated by Django 4.0.4 on 2022-08-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myservise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
