# Generated by Django 4.1 on 2022-08-23 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myservise', '0002_alter_books_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Died')),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book genre (e.g. Science Fiction, French Poetry etc.)', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='books',
            name='category',
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ForeignKey(help_text='Автор', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='myservise.authors'),
        ),
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.ManyToManyField(help_text='Категория книги', max_length=100, to='myservise.genres'),
        ),
    ]
